version: '3.8'

services:
  backend:
    container_name: backend
    image: ghcr.io/d1zero/f1-telemetry-scan/backend:1.0.0
    ports:
      - "20777:20777/udp"

  frontend:
    container_name: frontend
    image: ghcr.io/d1zero/f1-telemetry-scan/frontend:1.0.0
    build:
      context: ..
      dockerfile: .deploy/frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend