version: '3.8'

services:
  backend:
    container_name: backend
    image: ghcr.io/d1zero/f1-telemetry-scan/backend:latest
    ports:
      - "20777:20777/udp"

  frontend:
    container_name: frontend
    image: ghcr.io/d1zero/f1-telemetry-scan/frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend