name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      backend-version:
        description: 'Version to use for the Backend Docker image'
        required: true
        default: '1.0.0'

      frontend-version:
        description: 'Version to use for the Frontend Docker image'
        required: true
        default: '1.0.0'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.26.0"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for backend (amd64)
        run: |
          docker build --platform linux/amd64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/backend:${{ github.event.inputs.backend-version }} .
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.event.inputs.backend-version }}

      - name: Build and push Docker image for backend (arm64)
        run: |
          docker build --platform linux/arm64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/backend:${{ github.event.inputs.backend-version }} .
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.event.inputs.backend-version }}

      - name: Build and push Docker image for backend with latest tag (amd64)
        run: |
          docker build --platform linux/amd64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/backend:latest .
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build and push Docker image for backend with latest tag (arm64)
        run: |
          docker build --platform linux/arm64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/backend:latest .
          docker push ghcr.io/${{ github.repository }}/backend:latest

  build-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for frontend (amd64)
        run: |
          docker build --platform linux/amd64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/frontend:${{ github.event.inputs.frontend-version }} .
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.event.inputs.frontend-version }}

      - name: Build and push Docker image for frontend (arm64)
        run: |
          docker build --platform linux/arm64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/frontend:${{ github.event.inputs.frontend-version }} .
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.event.inputs.frontend-version }}

      - name: Build and push Docker image for frontend with latest tag (amd64)
        run: |
          docker build --platform linux/amd64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/frontend:latest .
          docker push ghcr.io/${{ github.repository }}/frontend:latest

      - name: Build and push Docker image for frontend with latest tag (arm64)
        run: |
          docker build --platform linux/arm64 -f .deploy/frontend.Dockerfile -t ghcr.io/${{ github.repository }}/frontend:latest .
          docker push ghcr.io/${{ github.repository }}/frontend:latest